'on':
  push:
    branches:
      - master
env:
  BUCKET_NAME: niazbaharudeen.com
  AWS_REGION: us-east-1
  DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
jobs:
  sync-s3:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::205930627269:role/S3-Sync-Github-Actions-Role
          role-session-name: s3-role-session
          aws-region: ${{ env.AWS_REGION }}
      - name: sync s3
        run: aws s3 sync . s3://${{ env.BUCKET_NAME }}/ --delete
      - name: invalidate caches
          
        run: aws cloudfront create-invalidation --distribution-id ${{ env.DISTRIBUTION_ID }} --paths "/*"